### GET request get users
GET http://localhost:8088/api/users
Accept: application/json

### GET request create users
POST http://localhost:8088/api/users
Accept: application/json


### GET request get products
GET http://localhost:8089/api/products
Accept: application/json

### GET request get products
GET http://localhost:8089/api/product/1
Accept: application/json

### GET request create products
POST http://localhost:8089/api/products
Accept: application/json


